### ISSUE TITLE
HELP: Analysis not flagging the issues from prior launch

### ISSUE THREAD

**Issue by mcafeerun** [reportportal/service-analyzer#19]
Hi,

I have a project with Auto analysis ON.

![image](https://user-images.githubusercontent.com/36393899/42654894-36ee6df6-85e8-11e8-86b4-b368956c2a03.png)

After my first launch, i have updated the defect type for all failed test. Then again i did ran the same test, but the auto analysis did not flag those defects with the reason i provided in my previous run. It remains in To Investigate status. Even i try manually to choose "Analysis" against the launch, still nothing happen. 
Can you pls help me understand what i'm missing here? 

Note: I see elastic search service is always in restarting status.

$ docker ps

```
CONTAINER ID        IMAGE                                      COMMAND                  CREATED             STATUS                         PORTS                                                                      NAMES
02f91f9655cd        reportportal/service-analyzer:4.2.0        "/service-analyzer"      7 minutes ago       Up 7 minutes                   8080/tcp                                                                   reportportal_analyzer_1
efefb0d82d57        reportportal/service-index:4.2.0           "/service-index"         7 minutes ago       Up 7 minutes                   8080/tcp                                                                   reportportal_index_1
818118a05fe3        reportportal/service-rally:4.2.0           "/start.sh"              7 minutes ago       Up 7 minutes                   8080/tcp                                                                   reportportal_rally_1
210df217ccb0        traefik:1.5                                "/traefik --consul..."   7 minutes ago       Up 7 minutes                   80/tcp, 0.0.0.0:8080-8081->8080-8081/tcp                                   reportportal_gateway_1
cd403c57a3b0        reportportal/service-authorization:4.2.0   "/start.sh"              7 minutes ago       Up 7 minutes                   8080/tcp                                                                   reportportal_uat_1
68db2d72451d        reportportal/service-api:4.2.1             "/start.sh"              7 minutes ago       Up 7 minutes                   8080/tcp                                                                   reportportal_api_1
8d2389ed4775        elastic/elasticsearch:6.1.1                "/usr/local/bin/do..."   7 minutes ago       Restarting (1) 2 minutes ago                                                                              reportportal_elasticsearch_1
90a30c327caf        consul:1.0.6                               "docker-entrypoint..."   7 minutes ago       Up 7 minutes                   8300-8302/tcp, 8301-8302/udp, 8600/tcp, 8600/udp, 0.0.0.0:8500->8500/tcp   reportportal_registry_1
fc958c3a0326        reportportal/service-ui:4.2.2              "/service-ui"            7 minutes ago       Up 7 minutes                   8080/tcp     
```

**Comment by evjlobanova** [comment]
@mcafeerun have many items you have already investigate? You have in settings parameter MiDocFreq 7, it means you should have in the index at least seven docs with error log that have at least one word from the analyzed log.
I can recommend you change MinDocFreq from 7 to 1, or increase number of analyzed items.

**Comment by evjlobanova** [comment]
@mcafeerun if you still have a problem or if the aa results are not relevant, please let me know. I will help you to choose right configurations. Also if you need consultation about AA, let me know please

**Comment by mcafeerun** [comment]
@evjlobanova  Thanks much for your inputs.. i will try the solution you provided and get back.. For now i'm closing the issue. thanks again!

**Comment by mcafeerun** [comment]
@evjlobanova  i tweaked the MinDocFreq from 7 to 1 and also increased the number of launches up to 7 (analyzed items).. Still i don't see anything is happening. Not sure what i'm missing.

PS: Any info/reference manual on this AA will be much helpful to tweak my project.

**Comment by evjlobanova** [comment]
@mcafeerun here is our documentation about AA http://reportportal.io/docs/Auto-Analysis-of-launches
Could you please perform following actions and send me screenshot
![image](https://user-images.githubusercontent.com/30413511/42807167-c5258e5a-89b8-11e8-9471-e20d8732171c.png)

Firstly, you should check if you have any docs in the Index. 

We can set up a call via skype and we can help you to configure analyzer for your needs

**Comment by mcafeerun** [comment]
@evjlobanova My apologies for delayed follow-up.. I got to pull off from this work for a while. 

Much appreciate your support!

Can you please help me understand, where do we store the index docs? I mean which collection in mongoDB. I will verify if we have any docs in it. 

BTW, I tried the steps you have provided. But still,  http://myhost:9200/_cat/indices?v is not reachable. 
```
  analyzer:
    image: 'reportportal/service-analyzer:4.2.0'
    depends_on:
      - registry
      - gateway
      - elasticsearch
    restart: always
  elasticsearch:
    image: 'elastic/elasticsearch:6.1.1'
    ports:
        - '9200:9200'
    restart: always
    volumes:
      - './data/elasticsearch:/usr/share/elasticsearch/data'
    environment:
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1

```

Also, i want to bring to your attention that,  **reportportal_elasticsearch_1** service is always in restarting status. 

$ docker ps
```
CONTAINER ID        IMAGE                                      COMMAND                  CREATED             STATUS                         PORTS                                                                      NAMES
dead467ccec9        reportportal/service-index:4.2.0           "/service-index"         12 minutes ago      Up 11 minutes                  8080/tcp                                                                   reportportal_index_1
138cdba0722f        reportportal/service-analyzer:4.2.0        "/service-analyzer"      12 minutes ago      Up 11 minutes                  8080/tcp                                                                   reportportal_analyzer_1
6c515f5f1bd0        reportportal/service-rally:4.2.0           "/start.sh"              12 minutes ago      Up 12 minutes                  8080/tcp                                                                   reportportal_rally_1
102f016ad4b2        reportportal/service-api:4.2.1             "/start.sh"              12 minutes ago      Up 12 minutes                  8080/tcp                                                                   reportportal_api_1
ee791724c8b4        traefik:1.5                                "/traefik --consul..."   12 minutes ago      Up 12 minutes                  80/tcp, 0.0.0.0:8080-8081->8080-8081/tcp                                   reportportal_gateway_1
60f097f4ad3d        reportportal/service-authorization:4.2.0   "/start.sh"              12 minutes ago      Up 12 minutes                  8080/tcp                                                                   reportportal_uat_1
0f54e4dd0b52        elastic/elasticsearch:6.1.1                "/usr/local/bin/do..."   12 minutes ago      Restarting (1) 4 minutes ago                                                                              reportportal_elasticsearch_1
1eab434db618        reportportal/service-ui:4.2.2              "/service-ui"            12 minutes ago      Up 12 minutes                  8080/tcp                                                                   reportportal_ui_1
22d0683780b2        consul:1.0.6                               "docker-entrypoint..."   12 minutes ago      Up 12 minutes                  8300-8302/tcp, 8301-8302/udp, 8600/tcp, 8600/udp, 0.0.0.0:8500->8500/tcp   reportportal_registry_1
```

I did some digging in the logs.. I see elastic search is failing.. 

$ docker-compose -p reportportal logs analyzer
```
analyzer_1       | [2018-08-19 00:51:28] ERROR Cannot send request to ES: Get http://elasticsearch:9200/_cluster/health: dial tcp: lookup elasticsearch on 127.0.0.11:53: server misbehaving
analyzer_1       | [2018-08-19 00:51:29] DEBUG Starting analysis for 1 launches
analyzer_1       | [2018-08-19 00:51:29] ERROR Cannot send request to ES: Get http://elasticsearch:9200/web_gateway_hcp/log/_search: dial tcp: lookup elasticsearch on 127.0.0.11:53: server misbehaving
analyzer_1       | time="2018-08-19T00:51:29Z" level=info msg="HTTP 500 - Cannot send request to ES: Get http://elasticsearch:9200/web_gateway_hcp/log/_search: dial tcp: lookup elasticsearch on 127.0.0.11:53: server misbehaving"
analyzer_1       | [2018-08-19 00:51:33] ERROR Cannot send request to ES: Get http://elasticsearch:9200/_cluster/health: dial tcp: lookup elasticsearch on 127.0.0.11:53: server misbehaving
analyzer_1       | [2018-08-19 00:51:38] ERROR Cannot send request to ES: Get http://elasticsearch:9200/_cluster/health: dial tcp: lookup elasticsearch on 127.0.0.11:53: server misbehaving
analyzer_1       | [2018-08-19 00:51:43] ERROR Cannot send request to ES: Get http://elasticsearch:9200/_cluster/health: dial tcp: lookup elasticsearch on 127.0.0.11:53: server misbehaving
analyzer_1       | [2018-08-19 00:51:48] ERROR Cannot send request to ES: Get http://elasticsearch:9200/_cluster/health: dial tcp: lookup elasticsearch on 127.0.0.11:53: server misbehaving
analyzer_1       | [2018-08-19 00:51:53] ERROR Cannot send request to ES: Get http://elasticsearch:9200/_cluster/health: dial tcp: lookup elasticsearch on 127.0.0.11:53: server misbehaving
```
$ docker-compose -p reportportal logs elasticsearch
```
Attaching to reportportal_elasticsearch_1
elasticsearch_1  | [2018-08-19T00:48:09,962][INFO ][o.e.n.Node               ] [] initializing ...
elasticsearch_1  | [2018-08-19T00:48:09,977][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
elasticsearch_1  | org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Failed to create node environment
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:125) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:85) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  | Caused by: java.lang.IllegalStateException: Failed to create node environment
elasticsearch_1  |      at org.elasticsearch.node.Node.<init>(Node.java:266) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:322) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      ... 6 more
elasticsearch_1  | Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes
elasticsearch_1  |      at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84) ~[?:?]
elasticsearch_1  |      at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:?]
elasticsearch_1  |      at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:?]
elasticsearch_1  |      at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384) ~[?:?]
elasticsearch_1  |      at java.nio.file.Files.createDirectory(Files.java:674) ~[?:1.8.0_151]
elasticsearch_1  |      at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781) ~[?:1.8.0_151]
elasticsearch_1  |      at java.nio.file.Files.createDirectories(Files.java:767) ~[?:1.8.0_151]
elasticsearch_1  |      at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:204) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.node.Node.<init>(Node.java:263) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:322) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      ... 6 more
```

**Comment by evjlobanova** [comment]
@mcafeerun hello! Here I have prepared steps how to resolve issues with analyzer http://reportportal.io/docs/How-to-resolve .

I suppose you didn`t give right permissions to ElasticSearch Services before installations. Could you please check link and try to follow the steps. If you still have a problem, please give me know and we can set up a call.

**Comment by mcafeerun** [comment]
Thank much! I will try this out and get back to you.

**Comment by evjlobanova** [comment]
@mcafeerun could you please share with your results?

**Comment by mcafeerun** [comment]
Hi @evjlobanova,

Sorry for delayed response.. Since i was busy with other priorities, i couldn't get back to you. 

The link you have provided is no longer working. Did you move this to another location?

**Comment by evjlobanova** [comment]
http://reportportal.io/docs/Issues-with-Analyzer:

**Comment by mcafeerun** [comment]
hi, @evjlobanova ,

I did all the steps you have given. Even i try to run the container as root. Still no luck. You could see the elasticsearch service is always in restarting stats.

Looking for you help to move forward.

$ docker ps
```
CONTAINER ID        IMAGE                                      COMMAND                  CREATED             STATUS                         PORTS                                                                      NAMES
265c2223e118        reportportal/service-analyzer:4.2.0        "/service-analyzer"      43 seconds ago      Up 40 seconds                  8080/tcp                                                                   reportportal_analyzer_1
1b4105f3e842        reportportal/service-index:4.2.0           "/service-index"         43 seconds ago      Up 40 seconds                  8080/tcp                                                                   reportportal_index_1
196731a5db69        traefik:1.5                                "/traefik --consul..."   45 seconds ago      Up 42 seconds                  80/tcp, 0.0.0.0:8080-8081->8080-8081/tcp                                   reportportal_gateway_1
7294fe5bd325        reportportal/service-ui:4.2.2              "/service-ui"            45 seconds ago      Up 43 seconds                  8080/tcp                                                                   reportportal_ui_1
97d5e5275c72        consul:1.0.6                               "docker-entrypoint..."   45 seconds ago      Up 43 seconds                  8300-8302/tcp, 8301-8302/udp, 8600/tcp, 8600/udp, 0.0.0.0:8500->8500/tcp   reportportal_registry_1
fb7e595337c9        reportportal/service-api:4.2.1             "/start.sh"              45 seconds ago      Up 43 seconds                  8080/tcp                                                                   reportportal_api_1
36b5f5737924        reportportal/service-rally:4.2.0           "/start.sh"              45 seconds ago      Up 43 seconds                  8080/tcp                                                                   reportportal_rally_1
4fdca72fd329        elastic/elasticsearch:6.1.1                "/usr/local/bin/do..."   45 seconds ago      Restarting (1) 2 seconds ago                                                                              reportportal_elasticsearch_1
4e927db90a67        reportportal/service-authorization:4.2.0   "/start.sh"              45 seconds ago      Up 42 seconds                  8080/tcp 
```

$ docker-compose -p reportportal logs --tail="all" analyzer
```
Attaching to reportportal_analyzer_1
analyzer_1       | 2018/10/05 02:11:19 Service Registered!
analyzer_1       | 2018/10/05 02:11:19 Starting on port 8080
analyzer_1       | [2018-10-05 02:11:22] ERROR Cannot send request to ES: Get http://elasticsearch:9200/_cluster/health: dial tcp 172.18.0.7:9200: connect: connection refused
analyzer_1       | [2018-10-05 02:11:27] ERROR Cannot send request to ES: Get http://elasticsearch:9200/_cluster/health: dial tcp 172.18.0.7:9200: connect: connection refused
analyzer_1       | [2018-10-05 02:11:32] ERROR Cannot send request to ES: Get http://elasticsearch:9200/_cluster/health: dial tcp 172.18.0.7:9200: connect: connection refused
analyzer_1       | [2018-10-05 02:11:37] ERROR Cannot send request to ES: Get http://elasticsearch:9200/_cluster/health: dial tcp 172.18.0.7:9200: connect: connection refused
analyzer_1       | [2018-10-05 02:11:42] ERROR Cannot send request to ES: Get http://elasticsearch:9200/_cluster/health: dial tcp 172.18.0.7:9200: connect: connection refused
analyzer_1       | [2018-10-05 02:11:48] ERROR Cannot send request to ES: Get http://elasticsearch:9200/_cluster/health: dial tcp 172.18.0.7:9200: connect: connection refused
analyzer_1       | [2018-10-05 02:11:53] ERROR Cannot send request to ES: Get http://elasticsearch:9200/_cluster/health: dial tcp: lookup elasticsearch on 127.0.0.11:53: server misbehaving
analyzer_1       | [2018-10-05 02:11:58] ERROR Cannot send request to ES: Get http://elasticsearch:9200/_cluster/health: dial tcp: lookup elasticsearch on 127.0.0.11:53: server misbehaving
analyzer_1       | [2018-10-05 02:12:03] ERROR Cannot send request to ES: Get http://elasticsearch:9200/_cluster/health: dial tcp: lookup elasticsearch on 127.0.0.11:53: server misbehaving
analyzer_1       | [2018-10-05 02:12:08] ERROR Cannot send request to ES: Get http://elasticsearch:9200/_cluster/health: dial tcp: lookup elasticsearch on 127.0.0.11:53: server misbehaving
```

$ docker-compose -p reportportal logs --tail="all" elasticsearch
```
Attaching to reportportal_elasticsearch_1
elasticsearch_1  | [2018-10-05T02:11:14,325][INFO ][o.e.n.Node               ] [] initializing ...
elasticsearch_1  | [2018-10-05T02:11:14,340][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
elasticsearch_1  | org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Failed to create node environment
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:125) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:85) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  | Caused by: java.lang.IllegalStateException: Failed to create node environment
elasticsearch_1  |      at org.elasticsearch.node.Node.<init>(Node.java:266) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:322) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      ... 6 more
elasticsearch_1  | Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes
elasticsearch_1  |      at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84) ~[?:?]
elasticsearch_1  |      at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:?]
elasticsearch_1  |      at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:?]
elasticsearch_1  |      at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384) ~[?:?]
elasticsearch_1  |      at java.nio.file.Files.createDirectory(Files.java:674) ~[?:1.8.0_151]
elasticsearch_1  |      at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781) ~[?:1.8.0_151]
elasticsearch_1  |      at java.nio.file.Files.createDirectories(Files.java:767) ~[?:1.8.0_151]
elasticsearch_1  |      at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:204) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.node.Node.<init>(Node.java:263) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:322) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-6.1.1.jar:6.1.1]

```

docker-compose.yml

```
version: '2'
services:
  registry:
    image: 'consul:1.0.6'
    volumes:
      - './data/consul:/consul/data'
    ports:
      - '8500:8500'
    command: agent -server -bootstrap-expect=1 -ui -client 0.0.0.0
    environment:
      - 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}'
    restart: always
  uat:
    image: 'reportportal/service-authorization:4.2.0'
    environment:
      - RP_PROFILES=docker
      - RP_SESSION_LIVE=86400
      - >-
        RP_MONGO_URI=mongodb://remote.host:27017/reportportal?authSource=reportportal
    restart: always
  gateway:
    image: 'traefik:1.5'
    ports:
      - '8080:8080'
      - '8081:8081'
    command:
      - '--consulcatalog.endpoint=registry:8500'
      - '--defaultEntryPoints=http'
      - '--entryPoints=Name:http Address::8080'
      - '--logLevel=DEBUG'
      - '--web'
      - '--web.address=:8081'
    restart: always
  index:
    image: 'reportportal/service-index:4.2.0'
    environment:
      - RP_SERVER_PORT=8080
      - RP_PROXY_CONSUL=true
    depends_on:
      - registry
      - gateway
    restart: always
  api:
    image: 'reportportal/service-api:4.2.1'
    environment:
      - RP_PROFILES=docker
      - 'JAVA_OPTS=-Xmx1g -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp'
      - >-
        RP_MONGO_URI=mongodb://remote.host:27017/reportportal?authSource=reportportal
    restart: always
  ui:
    image: 'reportportal/service-ui:4.2.2'
    environment:
      - RP_SERVER.PORT=8080
      - RP_CONSUL.TAGS=urlprefix-/ui opts strip=/ui
      - 'RP_CONSUL.ADDRESS=registry:8500'
    restart: always
  analyzer:
    image: 'reportportal/service-analyzer:4.2.0'
    depends_on:
      - registry
      - gateway
      - elasticsearch
    restart: always
  elasticsearch:
    image: 'elastic/elasticsearch:6.1.1'
    user: root
    ports:
        - '9200:9200'
    restart: always
    volumes:
      - './data/elasticsearch:/usr/share/elasticsearch/data'
    environment:
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
  rally:
    image: 'reportportal/service-rally:4.2.0'
    environment:
      - RP_PROFILES=docker
      - >-
        RP_MONGO_URI=mongodb://remotehost:27017/reportportal?authSource=reportportal
    restart: always
```
Note: remotehost:27017 is a masked name.
